#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/elearningdb
#    username: root
#    password: Theanh@123
##    password: sapassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        enable_lazy_load_no_trans: true
#      hibernate.jdbc.lob.non_contextual_creation: true
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#    enabled: true
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#cloudinary:
#  url: cloudinary://632641588972872:O1Ik4PlUtr5WZ6-1g6x_xbuLYdU@dwzjxsdli
#
#logging:
#  level:
#    root: INFO
#    org.springframework.data.repository: DEBUG
#

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elearningdb
    username: root
    password: Theanh@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # An toàn khi chạy local

# Cấu hình cloudinary cho local (nếu bạn muốn)
# Nếu không, nó sẽ báo lỗi, bạn có thể tạo 1 biến môi trường
# CLOUDINARY_URL trên máy local của bạn
# cloudinary:
#  url: cloudinary://... (url của bạn)

dev:
  nguyen: Nguyen-The-Anh